config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'demo_pages/demo1'
  get 'demo_pages/demo2'
  get 'demo_pages/demo3'

  resources :samples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => 'samples#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demo_pages_controller.rb
class DemoPagesController < ApplicationController
  def demo1
  end

  def demo2
  end
  
  def demo3
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
    @categories = Sample.pluck(:category).uniq
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:name, :url, :description, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_pages_helper.rb
module DemoPagesHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/demo_pages/demo1.html.erb
<div class="container">
    <h3>Google Map APIを使ったアプリケーション</h3>
    <div class="row">
        <div class="col-md-3">
            <div class="ui-area">
                <h4>マーカーの緯度経度</h4>
                <label for="lat">緯度</label>
                <input id="lat" type="text" value="35.681" onchange="refreshMap();" />
                <label for="lng">経度</label>
                <input id="lng" type="text" value="139.767" onchange="refreshMap();" />
                <hr />
        
                <h4>現在地の表示</h4>
                <button onclick="setCurrentPosition();" class="btn btn-primary">マップの中心を現在地に移動させる</button>
            </div>
        </div>
        <div class="col-md-9">
            <div id="map" style="height:400px;"></div>
        </div>
    </div>
</div>


<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCqIK64BjWyaxMmsQZQnMizK3_tl9YYbyU&callback=initMap">
</script>
<script>
    var map = null;
    var marker = null;
    var currentPositionMarker = null;
    var infoWindow = null;
    
    function setCurrentPosition() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success, error);
        } else {
            handleLocationError(false, infoWindow, map.getCenter());
        }
        
        function success(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            
            if(infoWindow) {
                infoWindow.setMap(null);
                infoWindow = null;
            }
            infoWindow = new google.maps.InfoWindow({map: map});
            infoWindow.setPosition(pos);
            infoWindow.setContent('Location found.');
            map.setCenter(pos);            
        }
        
        function error(err) {
            handleLocationError(true, infoWindow, map.getCenter());
        }
        
        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
        }
            
    }
    
    function refreshMap() {
        var lat = parseFloat($("#lat").val());
        var lng = parseFloat($("#lng").val());
        
        marker.setPosition({lat: lat, lng: lng});
    }
    function initMap() {
        
        var lat = parseFloat($("#lat").val());
        var lng = parseFloat($("#lng").val());
        
        var tokyo = {lat: lat, lng: lng};
        
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: tokyo
        });
        marker = new google.maps.Marker({
            position: tokyo,
            map: map,
            draggable: true
        });
        marker.addListener('drag', function() {
            var latlng = marker.getPosition();
            $("#lat").val(latlng.lat());
            $("#lng").val(latlng.lng());
        });
    }
</script>

app/views/demo_pages/demo2.html.erb
<div class="container">
    <h3>グラフアプリケーション</h3>
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <!--<li class="active"><a href="#">Chart.js</a></li>-->
                <li id="chartjs"><a href="" onclick="drawChartJs(); return false;">Chart.js</a></li>
                <li id="googlechart"><a href="" onclick="drawGoogleChart(); return false;">Google Chart API</a></li>
                <li id="canvasjs"><a href="" onclick="drawCanvasJs(); return false;">Canvas.js</a></li>
            </ul>
        </div>
        <div class="col-md-9" style="margin-bottom:50px;">
            <h4>公式URL</h4>
            <div><a id="url" href="" target="_blank"></a></div>
            <hr />
            
            <h4>折れ線グラフ</h4>
            <div id="line_chart_div"></div>
            <div id="container_canvas_line" style="width:100%">
                <canvas id="line_chart_canvas"></canvas>
            </div>
            
            <h4>棒グラフ</h4>
            <div id="bar_chart_div"></div>
            <div id="container_canvas_bar" style="width:100%">
                <canvas id="bar_chart_canvas"></canvas>
            </div>
        </div>
    </div>
    
</div>

<!-- Global -->
<script>
    var data_x = ["1月","2月","3月","4月","5月","6月","7月"];
    var bardata_y = [35, 40, 60, 71, 96, 75, 50];
    var linedata_y = [65, 59, 80, 81, 56, 55, 40];
    
    function initDisplay() {
        // グラフ描画スペースのクリア
        $("#line_chart_div").html("");
        $("#container_canvas_line").html('<canvas id="line_chart_canvas"></canvas>');
        $("#bar_chart_div").html("");
        $("#container_canvas_bar").html('<canvas id="bar_chart_canvas"></canvas>');
        
        // サイドバーのクリア
        $("#chartjs").attr("class", "");
        $("#googlechart").attr("class", "");
        $("#canvasjs").attr("class", "");
        
        // divの高さ初期化
        $("#line_chart_div").height(0);
        $("#bar_chart_div").height(0);

    }

    $(function() {
        drawChartJs(); 
    });
</script>



<!-- Chart.js -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
<script>
    function drawChartJs() {
        initDisplay();
        
        // サイドバーのアクティブ化
        $("#chartjs").attr("class", "active");
        
        // URLの挿入
        var url = "http://www.chartjs.org/";
        $("#url").attr("href", url);
        $("#url").html(url);
        
        // データの作成
        var elem_line = document.getElementById("line_chart_canvas").getContext("2d");
        var elem_bar = document.getElementById("bar_chart_canvas").getContext("2d");
        
        // 折れ線グラフ
        var data_line = {
            type: 'line',
            data: {
                labels: data_x, //x軸
                datasets: [
                    {
                        label: "sample_line_chart",
                        data: linedata_y  //y軸
                    }
                ]
            },
            options: {
                responsive: true,
            }
        }
        
        // 棒グラフ
        var data_bar = {
            type: 'bar',
            data: {
                labels: data_x, //x軸
                datasets: [
                    {
                        label: "sample_bar_chart",
                        data: bardata_y  //y軸
                    }
                ]
            },
            options: {
                responsive: true,
            }
        };
        var myLineChart = new Chart(elem_line, data_line);
        var myBarChart = new Chart(elem_bar, data_bar);
    }
</script>

<!-- Google Chart API -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    google.charts.load('current', {'packages':['corechart','line','bar']});
</script>
<script>
    function drawGoogleChart() {
        initDisplay();
        
        // サイドバーのアクティブ化
        $("#googlechart").attr("class", "active");
        
        $("#line_chart_div").height(400);
        $("#bar_chart_div").height(400);
        
        // URLの挿入
        var url = "https://developers.google.com/chart/";
        $("#url").attr("href", url);
        $("#url").html(url);
        
        var data_line = new google.visualization.DataTable();
        data_line.addColumn("string", "month");
        data_line.addColumn("number", "data");
        
        data_line.addRows([
            [data_x[0],  linedata_y[0]],
            [data_x[1],  linedata_y[1]],
            [data_x[2],  linedata_y[2]],
            [data_x[3],  linedata_y[3]],
            [data_x[4],  linedata_y[4]],
            [data_x[5],  linedata_y[5]],
            [data_x[6],  linedata_y[6]]
        ]);

        var data_bar = new google.visualization.DataTable();
        data_bar.addColumn("string", "month");
        data_bar.addColumn("number", "data");
        
        data_bar.addRows([
            [data_x[0],  bardata_y[0]],
            [data_x[1],  bardata_y[1]],
            [data_x[2],  bardata_y[2]],
            [data_x[3],  bardata_y[3]],
            [data_x[4],  bardata_y[4]],
            [data_x[5],  bardata_y[5]],
            [data_x[6],  bardata_y[6]]
        ]);
        var options = {
            width: "100%",
            height: 400
        };
        var chart_line = new google.charts.Line(document.getElementById('line_chart_div'));
        var chart_bar = new google.charts.Bar(document.getElementById('bar_chart_div'));
        chart_line.draw(data_line, google.charts.Line.convertOptions(options));
        chart_bar.draw(data_bar, google.charts.Bar.convertOptions(options));
        
    }
</script>

<!-- canvas.js -->
<!-- vendor/assetに配置し、アセットパイプラインでインポート -->
<script>
    function drawCanvasJs() {
        initDisplay();
        
        // サイドバーのアクティブ化
        $("#canvasjs").attr("class", "active");
        
        $("#line_chart_div").height(400);
        $("#bar_chart_div").height(400);
        
        // URLの挿入
        var url = "http://canvasjs.com/";
        $("#url").attr("href", url);
        $("#url").html(url);
        
        var linechart = new CanvasJS.Chart("line_chart_div",
        {
          theme: "theme2",
          title:{
            text: "Earthquakes - per month"
          },
          animationEnabled: true,
          axisX: {
            valueFormatString: "MMM",
            interval:1,
            intervalType: "month"
            
          },
          axisY:{
            includeZero: false
            
          },
          data: [
          {        
            type: "line",
            //lineThickness: 3,        
            dataPoints: [
            { x: new Date(2012, 00, 1), y: 450 },
            { x: new Date(2012, 01, 1), y: 414},
            { x: new Date(2012, 02, 1), y: 520, indexLabel: "highest",markerColor: "red", markerType: "triangle"},
            { x: new Date(2012, 03, 1), y: 460 },
            { x: new Date(2012, 04, 1), y: 450 },
            { x: new Date(2012, 05, 1), y: 500 },
            { x: new Date(2012, 06, 1), y: 480 },
            { x: new Date(2012, 07, 1), y: 480 },
            { x: new Date(2012, 08, 1), y: 410 , indexLabel: "lowest",markerColor: "DarkSlateGrey", markerType: "cross"},
            { x: new Date(2012, 09, 1), y: 500 },
            { x: new Date(2012, 10, 1), y: 480 },
            { x: new Date(2012, 11, 1), y: 510 }
            
            ]
          }
          
          
          ]
        });
    
        linechart.render();        
    	var chart = new CanvasJS.Chart("bar_chart_div", {
    		theme: "theme2",//theme1
    		title:{
    			text: "Basic Column Chart - CanvasJS"              
    		},
    		animationEnabled: false,   // change to true
    		data: [              
    		{
    			// Change type to "bar", "area", "spline", "pie",etc.
    			type: "column",
    			dataPoints: [
    				{ label: "apple",  y: 10  },
    				{ label: "orange", y: 15  },
    				{ label: "banana", y: 25  },
    				{ label: "mango",  y: 30  },
    				{ label: "grape",  y: 28  }
    			]
    		}
    		]
    	});
    	chart.render();
    }
</script>

app/views/demo_pages/demo3.html.erb
<div class="container">
    <h3>スライダー</h3>
    <div class="row">
        <div class="col-md-12" style="max-width:600px;">
            <div class="flexslider">
                <ul class="slides">
                    <li>
                        <%= image_tag("flexslider/kitchen_adventurer_caramel.jpg") %>
                    </li>
                    <li>
                        <%= image_tag("flexslider/kitchen_adventurer_cheesecake_brownie.jpg") %>
                    </li>
                    <li>
                        <%= image_tag("flexslider/kitchen_adventurer_donut.jpg") %>
                    </li>
                    <li>
                        <%= image_tag("flexslider/kitchen_adventurer_lemon.jpg") %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Global -->
<script>
    $(window).load(function() {
        $('.flexslider').flexslider({
            animation: "slide",
            prevText: "",
            nextText: ""
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta  name="viewport" content="width=device-width">
    <title>サンプル集</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
    <footer>
      <p>COPYRIGHT &#169; torihon62 ALL RIGHTS RESERVED.	</p>
    </footer>
  </body>
</html>

app/views/samples/_form.html.erb
<%= form_for(sample) do |f| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<header class="jumbotron">
　<div class="container">
　　<h1>Samples</h1>
　</div> <!-- /container -->    
</header>

<div class="container">
  <div class="list-group">
    <% @categories.each do |category| %>
      <h3><%= category %></h3>
      <% @samples.each do |sample| %>
        <% if category == sample.category %>
      	<a class="list-group-item" href="<%= sample.url %>" target="_black">
      		<h4 class="list-group-item-heading"><%= sample.name %></h4>
      		<small><%= sample.description %></small>
      	</a>
      	<% end %>
    	<% end %>
    <% end %>
  </div>
</div>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sample.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @sample.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sample.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @sample.category %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>